LLReactiveMatchers: enforce class for sendError and sendValues.
Lightricks/LLReactiveMatchers pull request #7
Opened 2017-01-17 09:55 UTC by byohay

So there will be compile time error if sendError and sendValues are not of the right class.

2017-01-17 10:03 UTC, dlahyani commented
LGTM. 
@byohay Lets just make sure that all Foundations and Facetune tests compile and pass with this change.
@barakyoresh / @StatusReport  PTAL.

2017-01-18 10:12 UTC, StatusReport commented
I am not sure this is correct. The matchers extract a recorder from the given `expected` value, using this function:

```objc
extern LLSignalTestRecorder *LLRMRecorderForObject(id object) {
    if([object isKindOfClass:LLSignalTestRecorder.class]) {
        return object;
    } else if([object isKindOfClass:RACSignal.class]){
        return [LLSignalTestRecorder recordWithSignal:object];
    } else if([object isKindOfClass:NSArray.class]) {
        return [LLSignalTestRecorder recorderThatSendsValuesThenCompletes:object];
    } else if([object isKindOfClass:NSError.class]) {
        return [LLSignalTestRecorder recorderThatSendsValues:@[] thenErrors:object];
    }
    return nil;
}
```

So it doesn't have to be `NSError` and `NSArray`, but please verify me.

2017-01-18 12:58 UTC, barakyoresh commented
Asked Alex if he had any macro trickery in mind to enable all and only 4 types. He didn't have a good answer.

2017-01-18 16:49 UTC, byohay commented
@StatusReport You are correct, it accepts `RACSignal` and `LLSignalTestRecorder`, however:

- Foundations and Facetune compile successfully, thus no code uses this form of `sendError` and `sendValues`.
- Although this tries to achieve the same comparison as in comparing two ints (i.e., you compare a signal to a signal), I think this is less intuitive than the form we all use, that's why I think it can be dropped. I can add another `sendValuesAsSignal` that accepts a `RACSignal`, but I'm not sure it is needed.

This enforcement covers cases where you forget to wrap a single value with an array in `sendValues` and get a weird error.

2017-01-19 08:49 UTC, StatusReport commented
@byohay so maybe the problem is with the error reporting and not the "type safety" (in quotes since everything is covered by macros and hard to understand anyway)?

2017-01-19 11:46 UTC, byohay commented
Initially I added a meaningful error report, but I like this solution better because it fails in compile time and saves time developing. It does provide type safety, I tried to pass types other than `NSError` and `NSArray` and the compilation fails.

2017-01-19 13:29 UTC, StatusReport commented
I'm always a fan of compile time errors, but in this case it limits the functionality of the library, so I'd keep the run time error for now.

2017-02-01 14:32 UTC, StatusReport commented
@dlahyani please proceed with the PR.

2017-02-01 16:12 UTC, byohay commented
@dlahyani I added runtime error message in addition to the type enforcement, since passing `id` to `sendError/Values` still compiles successfully.

2017-03-15 10:35 UTC, byohay commented
@dlahyani ping.

2017-03-15 11:36 UTC, dlahyani requested changes
Please update the 'README.md' file in repo root folder, the code sample at the end of the file mentions that this matchers accept `RACSignal` and `LLSignalTestRecorder`.

2017-03-15 11:36 UTC, dlahyani commented on LLReactiveMatchers/LLReactiveMatchersHelpers.m
> +  return [object isKindOfClass:expectedClass];
Why do we need this function if this is all it is doing?

2017-03-15 11:36 UTC, dlahyani commented on LLReactiveMatchers/LLReactiveMatchersHelpers.m
> +  return [object isKindOfClass:expectedClass];
I guess this method was added just in order to keep LLRM "conventions". I suggest adding 2 different methods: `LLRMCorrectClassesForError` and `LLRMCorrectClassesForValues`.

2017-03-15 11:36 UTC, dlahyani commented on LLReactiveMatchers/LLReactiveMatchersMessageBuilder.m
> +  return [NSString stringWithFormat:@"expected: expected should be of class %@", correctClass];
should be -> to be

2017-03-16 09:57 UTC, byohay commented on LLReactiveMatchers/LLReactiveMatchersMessageBuilder.m
> +  return [NSString stringWithFormat:@"expected: expected should be of class %@", correctClass];
Fixed.

2017-03-16 10:00 UTC, byohay commented on LLReactiveMatchers/LLReactiveMatchersHelpers.m
> +  return [object isKindOfClass:expectedClass];
Done.

2017-03-16 10:01 UTC, byohay commented
Round complete.

2017-03-19 11:25 UTC, dlahyani approved these changes

2017-03-19 11:26 UTC, dlahyani commented
Squash.

2017-03-19 11:54 UTC, byohay commented
Squashed.

2017-03-19 12:02 UTC, merged